packages:
  - apps/*
  - modules/*

catalog:
  react: ^19.2.4
  react-dom: ^19.2.4
  zod: ^4.3.6
  drizzle-orm: ^0.45.1

onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - msw
  - nx
  - sharp
  - workerd
