packages:
  - apps/*
  - modules/*

allowBuilds:
  '@sentry/cli': true
  esbuild: true
  msw: true
  nx: true
  sharp: true
  workerd: true

catalog:
  react: ^19.3.0
  react-dom: ^19.3.0
  zod: ^4.5.1
