name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'
      - run: pnpm install
      - run: npx nx format:check
      - run: npx nx affected --target=build --parallel=3
        env:
          DATABASE_HOST: ${{ secrets.database_host_preview }}
          DATABASE_USERNAME: ${{ secrets.database_username_preview }}
          DATABASE_PASSWORD: ${{ secrets.database_password_preview }}
          AISWEB_API_KEY: ${{ secrets.aisweb_api_key }}
          AISWEB_API_PASSWORD: ${{ secrets.aisweb_api_password }}
          RPL_DATE: ${{ github.event.inputs.date }}
      - run: pnpm test
      - run: pnpm lint
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
