name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - name: Build application packages
        run: |
          yarn workspace @mach/common run build
          yarn workspace @mach/database run build
          yarn workspace @mach/rpl-crawler run build
      - run: yarn test
  build_rest_api:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/jpedroh/mach-rest-api:${{ github.sha }}
          file: ./packages/rest-api/Dockerfile
          build-args: APP_VERSION_ARG=${{ github.sha }}
          push: true
  build_rpl_crawler:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/jpedroh/mach-rpl-crawler:${{ github.sha }}
          file: ./packages/rpl-crawler/Dockerfile
          push: true
