name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "master"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: pnpm install
      - run: npx nx workspace-lint
      - run: npx nx affected --target=build --parallel=3
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: npx nx affected --target=test --parallel=3 --ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
