name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      TURSO_CONNECTION_URL: ${{ secrets.turso_connection_url }}
      TURSO_AUTH_TOKEN: ${{ secrets.turso_auth_token }}
      AISWEB_API_KEY: ${{ secrets.aisweb_api_key }}
      AISWEB_API_PASSWORD: ${{ secrets.aisweb_api_password }}
      NXCACHE_AWS_ACCESS_KEY_ID: ${{secrets.nxcache_aws_access_key_id}}
      NXCACHE_AWS_SECRET_ACCESS_KEY: ${{secrets.nxcache_aws_secret_access_key}}
      NXCACHE_AWS_ENDPOINT: ${{secrets.nxcache_aws_endpoint}}
      NXCACHE_AWS_REGION: ${{secrets.nxcache_aws_region}}
      NXCACHE_AWS_BUCKET: ${{secrets.nxcache_aws_bucket}}
      NXCACHE_AWS_FORCE_PATH_STYLE: ${{secrets.nxcache_aws_force_path_style}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'main'
      - run: pnpm install
      - run: npx sherif
      - run: npx nx format:check
      - run: npx nx affected --target=pack --parallel=3
      - run: npx nx affected --target=test --parallel=3
      - run: npx nx affected --target=lint --parallel=3
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
