name: Deploy
on:
  release:
    types:
      - created
jobs:
  build_front:
    runs-on: ubuntu-latest
    environment:
      name: front_production
      url: https://jpedroh.github.io/mach
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - run: pnpm install
      - run: npx nx run @mach/front:build
        env:
          VITE_APP_VERSION: ${{ github.event.release.tag_name }}
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/front/dist
