name: Deploy
on:
  release:
    types:
      - created
      - published
      - edited
jobs:
  build_rest_api:
    runs-on: ubuntu-latest
    environment:
      name: api_production
      url: https://mach-api.herokuapp.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - uses: docker/build-push-action@v2
        with:
          tags: |
            registry.heroku.com/mach-api/web:latest
            ghcr.io/jpedroh/mach-rest-api:latest
            ghcr.io/jpedroh/mach-rest-api:${{ github.ref }}
          file: ./packages/rest-api/Dockerfile
          build-args: APP_VERSION_ARG=${{ github.ref }}
          push: true
      - run: heroku container:release web -a mach-api
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  build_rpl_crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/jpedroh/mach-rest-api:latest
            ghcr.io/jpedroh/mach-rest-api:${{ github.ref }}
          file: ./packages/rpl-crawler/Dockerfile
          push: true
  build_front:
    runs-on: ubuntu-latest
    environment:
      name: front_production
      url: https://jpedroh.github.io/mach
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/jpedroh/mach-rest-api:latest
            ghcr.io/jpedroh/mach-rest-api:${{ github.ref }}
          file: ./packages/front/Dockerfile
          build-args: APP_VERSION_ARG=${{ github.ref }}
          push: true
      - run: yarn --frozen-lockfile
      - name: Run build
        run: |
          yarn workspace @mach/common build
          yarn workspace @mach/front build
        env:
          SKIP_PREFLIGHT_CHECK: true
          REACT_APP_APP_VERSION: ${{ github.ref }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/front/build
