name: E2E Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  playwright:
    services:
      libsql:
        image: ghcr.io/tursodatabase/libsql-server:ef44612
        ports:
          - 8080:8080
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    env:
      PLAYWRIGHT_TEST_BASE_URL: 'http://localhost:3000'
      TURSO_CONNECTION_URL: 'http://libsql:8080'
      TURSO_AUTH_TOKEN: 'secret'
      AISWEB_API_KEY: ${{ secrets.aisweb_api_key }}
      AISWEB_API_PASSWORD: ${{ secrets.aisweb_api_password }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v5.0.0
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm drizzle-kit push
      - run: echo "TURSO_CONNECTION_URL=http://libsql:8080\nTURSO_AUTH_TOKEN=secret" > apps/web/.dev.vars
      - run: HOME=/root pnpm e2e
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: playwright-report
          path: apps/web-e2e/test-output
          retention-days: 30
  rpl-crawler:
    services:
      libsql:
        image: ghcr.io/tursodatabase/libsql-server:ef44612
        ports:
          - 8080:8080
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-jammy
    env:
      TURSO_CONNECTION_URL: 'http://libsql:8080'
      TURSO_AUTH_TOKEN: 'secret'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v5.0.0
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm drizzle-kit push
      - run: node apps/rpl-crawler-cli/src/index.ts ${RPL_CRAWLER_DRY_RUN_DATE}
        env:
          AISWEB_API_KEY: ${{ secrets.aisweb_api_key }}
          AISWEB_API_PASSWORD: ${{ secrets.aisweb_api_password }}
          RPL_CRAWLER_DRY_RUN_DATE: ${{ vars.rpl_crawler_dry_run_date }}
