name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_e2e:
    services:
      libsql:
        image: ghcr.io/tursodatabase/libsql-server:ef44612
        ports:
          - 8080:8080
    name: Playwright tests
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-jammy
    env:
      PLAYWRIGHT_TEST_BASE_URL: 'http://localhost:3000'
      TURSO_CONNECTION_URL: 'http://libsql:8080'
      TURSO_AUTH_TOKEN: 'secret'
      AISWEB_API_KEY: ${{ secrets.aisweb_api_key }}
      AISWEB_API_PASSWORD: ${{ secrets.aisweb_api_password }}
      NXCACHE_AWS_ACCESS_KEY_ID: ${{secrets.nxcache_aws_access_key_id}}
      NXCACHE_AWS_SECRET_ACCESS_KEY: ${{secrets.nxcache_aws_secret_access_key}}
      NXCACHE_AWS_ENDPOINT: ${{secrets.nxcache_aws_endpoint}}
      NXCACHE_AWS_REGION: ${{secrets.nxcache_aws_region}}
      NXCACHE_AWS_BUCKET: ${{secrets.nxcache_aws_bucket}}
      NXCACHE_AWS_FORCE_PATH_STYLE: ${{secrets.nxcache_aws_force_path_style}}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm drizzle-kit push
      - run: echo "TURSO_CONNECTION_URL=http://libsql:8080\nTURSO_AUTH_TOKEN=secret" > apps/web/.dev.vars
      - run: HOME=/root pnpm e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/web-e2e/test-output
          retention-days: 30
