name: Run RPL Crawler
on:
  workflow_dispatch:
    inputs:
      date:
        description: "Date of publication of RPL (YYYY-MM-DD)"
        required: false
  schedule:
    - cron: "0 0 * * *"
jobs:
  update_rpl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - run: pnpm install
      - run: npx nx run @mach/rpl-crawler:build
      - run: node packages/rpl-crawler/dist/main SBAZ,SBBS,SBCW,SBRE ${RPL_DATE:-$(date +"%Y-%m-%d")}
        env:
          DATABASE_HOST: ${{ secrets.database_host_production }}
          DATABASE_USERNAME: ${{ secrets.database_username_production }}
          DATABASE_PASSWORD: ${{ secrets.database_password_production }}
          RPL_DATE: ${{ github.event.inputs.date }}
