## TODO: Switch to Docker containers

name: Run RPL Crawler
on: [push]
#  schedule:
#    - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install
        run: yarn
      - name: Lerna bootstrap
        run: yarn lerna bootstrap
      - name: Build rpl crawler
        run: yarn lerna run build
      - name: Run Update
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker run -v "$(pwd):/usr/src/" -w "/usr/src/" -e DATABASE_URL=$(heroku config:get DATABASE_URL --app=mach-api) node:alpine node packages/rpl-crawler/dist/main SBAZ,SBBS,SBCW,SBRE 2020-08-03
