name: Run RPL Crawler
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build Docker Image
        run: docker build -t mach-rpl-crawler -f ./packages/rpl-crawler/Dockerfile .
      - name: Run Update
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker run -e DATABASE_URL=$(heroku config:get DATABASE_URL --app=mach-api) mach-rpl-crawler node packages/rpl-crawler/dist/main SBAZ,SBBS,SBCW,SBRE $(date +"%Y-%m-%d")
