name: Run RPL Crawler
on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date of publication of RPL (YYYY-MM-DD)'
        required: false
  schedule:
    - cron: '0 0 * * *'
jobs:
  update_rpl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: npx nx run @mach/rpl-crawler:pack
      - run: node packages/rpl-crawler/dist ${RPL_DATE:-$(date +"%Y-%m-%d")}
        env:
          DATABASE_HOST: ${{ secrets.database_host_production }}
          DATABASE_USERNAME: ${{ secrets.database_username_production }}
          DATABASE_PASSWORD: ${{ secrets.database_password_production }}
          AISWEB_API_KEY: ${{ secrets.aisweb_api_key }}
          AISWEB_API_PASSWORD: ${{ secrets.aisweb_api_password }}
          RPL_DATE: ${{ github.event.inputs.date }}
