name: Run RPL Crawler
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update_rpl:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Update
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker run -e DATABASE_URL=$(heroku config:get DATABASE_URL --app=mach-api) ghcr.io/jpedroh/mach-rpl-crawler:latest node packages/rpl-crawler/dist/main SBAZ,SBBS,SBCW,SBRE $(date +"%Y-%m-%d")
