## TODO: Switch to Docker containers

name: Run RPL Crawler
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install
        run: yarn
      - name: Lerna bootstrap
        run: yarn lerna bootstrap
      - name: Build rpl crawler
        run: yarn lerna run build --scope=@mach/rpl-crawler
      - name: Run Update
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: node packages/rpl-crawler/dist/main SBAZ,SBBS,SBCW,SBRE $(date +"%Y-%m-%d") $(heroku config:get DATABASE_URL --app=mach-api)
