name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install
        run: yarn
      - name: Lerna bootstrap
        run: yarn lerna bootstrap
      - name: Build packages
        run: yarn build
      - name: Test
        run: yarn test