name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install
        run: yarn
      - name: Build packages
        run: |
          yarn workspace @mach/common run build
          yarn workspace @mach/database run build
          yarn workspace @mach/rest-api run build
          yarn workspace @mach/rpl-crawler run build
      - name: Test
        run: yarn test